name: Rust

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release && strip target/release/hemolymph-rs && mv target/release/hemolymph-rs target/release/hemolymph-rs_amd64

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: target/release/hemolymph-rs_amd64
